global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'otel-collector-metrics'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['otel-collector:1399']
    metric_relabel_configs:
      - source_labels: [exported_job]
        target_label: service
        action: replace  

